services:
  - type: web
    name: mojito-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URL
        value: mongodb+srv://yashitabahrani:yashita13@cluster0.gvcuuu0.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: PORT
        value: 5000
    rootDir: mojito-backend

  - type: web
    name: mojito-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    rootDir: .
